### ISSUE TITLE
Why does `Parsable` depend on `Display`?

### ISSUE THREAD

**Issue by vorner** [saschagrunert/peel#1]
Hello

Is there a good reason the `Parsable` trait depends on `Display`? If it's because of printing them to logs, `Debug` would look preferable to me ‒ logs are not really „pretty“ user output and `Debug` can be auto-derived, while `Display` must be written by hand, which is a bit annoying.

**Comment by saschagrunert** [comment]
Hey, yep I guess `Debug` would be enough here.
